name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas

      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 

      - name: Push mlruns to repo using secrets
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

          # Ubah URL origin agar bisa push dengan GH_TOKEN
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}

          git pull origin main --allow-unrelated-histories
          git add mlruns/
          git commit -m "CI: Save MLflow artifacts" || echo "Nothing to commit"
          git push origin main
